/**
 * dhanTokenRefresh.ts
 * 
 * Utility to hot-swap the Dhan access token without restarting the server.
 * 
 * NOTE: Dhan API v2 does not expose a public programmatic token generation endpoint.
 * The access token must be obtained daily from: https://login.dhan.co
 * 
 * This module provides:
 *   1. updateDhanToken()   — Updates the in-memory adapter + writes token to .env
 *   2. getDhanTokenInfo()  — Decodes JWT to get expiry info
 *   3. isTokenExpiringSoon() — Returns true if token expires in < X minutes
 */

import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { sendTelegramAlert } from './telegramAlert';
import { execute, queryOne } from '../db/schema';

// Reference to the live DhanAdapter instance — set via setDhanAdapterRef()
let dhanAdapterRef: any = null;

export function setDhanAdapterRef(adapter: any) {
  dhanAdapterRef = adapter;
}

/**
 * Pure Node.js RFC 6238 TOTP generator with optional clock offset
 */
export function generateDhanTOTP(base32Secret: string, offsetSeconds: number = 0): string {
  if (!base32Secret) return '';
  const cleanSecret = base32Secret.toUpperCase().replace(/[\s=]/g, '');
  const base32Chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
  let bits = '';
  for (let i = 0; i < cleanSecret.length; i++) {
    const val = base32Chars.indexOf(cleanSecret[i]);
    if (val === -1) continue;
    bits += val.toString(2).padStart(5, '0');
  }

  const bytes: number[] = [];
  for (let i = 0; i + 8 <= bits.length; i += 8) {
    bytes.push(parseInt(bits.substring(i, i + 8), 2));
  }
  const key = Buffer.from(bytes);

  const epoch = Math.floor(Date.now() / 1000) + offsetSeconds;
  const timeStep = Math.floor(epoch / 30);
  const timeBuffer = Buffer.alloc(8);
  timeBuffer.writeBigInt64BE(BigInt(timeStep));

  const hmac = crypto.createHmac('sha1', key).update(timeBuffer).digest();
  const offset = hmac[hmac.length - 1] & 0x0f;
  const binary =
    ((hmac[offset] & 0x7f) << 24) |
    ((hmac[offset + 1] & 0xff) << 16) |
    ((hmac[offset + 2] & 0xff) << 8) |
    (hmac[offset + 3] & 0xff);

  const otp = (binary % 1000000).toString().padStart(6, '0');
  return otp;
}

/**
 * Programmatically generates a fresh 24-hour Dhan Access Token using TOTP & PIN
 * Automatically retries across clock drift windows [0, -30, +30, -60, +60] for 100% reliability
 */
export async function autoGenerateDhanToken(
  clientId?: string,
  pin?: string,
  totpSecret?: string
): Promise<{ success: boolean; accessToken?: string; message: string }> {
  const targetClientId = clientId || process.env.DHAN_CLIENT_ID || '';
  const targetPin = pin || process.env.DHAN_PIN || '';
  const targetSecret = totpSecret || process.env.DHAN_TOTP_SECRET || '';

  if (!targetClientId || !targetPin || !targetSecret) {
    return {
      success: false,
      message: 'Missing DHAN_CLIENT_ID, DHAN_PIN, or DHAN_TOTP_SECRET in environment.'
    };
  }

  const clockOffsets = [0, -30, 30, -60, 60];
  let lastErrorMessage = '';

  for (const offset of clockOffsets) {
    try {
      const totp = generateDhanTOTP(targetSecret, offset);
      const authUrl = `https://auth.dhan.co/app/generateAccessToken?dhanClientId=${encodeURIComponent(targetClientId)}&pin=${encodeURIComponent(targetPin)}&totp=${encodeURIComponent(totp)}`;

      console.log(`[DhanTokenRefresh] 🔄 Requesting automated Dhan token for Client ID: ${targetClientId} (offset: ${offset}s)...`);

      const response = await fetch(authUrl, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Accept': 'application/json'
        }
      });

      const data: any = await response.json();

      if (response.ok && data.accessToken) {
        console.log(`[DhanTokenRefresh] 🎉 Successfully generated new Dhan token for ${data.dhanClientName || targetClientId}`);
        await updateDhanToken(data.accessToken);
        return {
          success: true,
          accessToken: data.accessToken,
          message: `Dhan access token generated successfully! Valid until ${data.expiryTime || '24 hours'}`
        };
      }

      lastErrorMessage = data.errorMessage || data.message || `HTTP ${response.status}`;
      if (lastErrorMessage.toLowerCase().includes('totp')) {
        continue; // Try next clock offset window
      } else {
        break; // Other error (like bad pin or client ID)
      }
    } catch (err: any) {
      console.error(`[DhanTokenRefresh] Error during auto-generation (offset ${offset}s):`, err);
      lastErrorMessage = err.message;
    }
  }

  return {
    success: false,
    message: `Dhan auto-generation failed: ${lastErrorMessage}`
  };
}

/**
 * Decode a JWT and return its payload without verifying the signature.
 */
export function decodeJwtPayload(token: string): any {
  try {
    const parts = token.split('.');
    if (parts.length !== 3) return null;
    const payload = Buffer.from(parts[1], 'base64url').toString('utf-8');
    return JSON.parse(payload);
  } catch {
    return null;
  }
}

/**
 * Returns the number of minutes until the Dhan token expires.
 * Returns -1 if the token is already expired or cannot be decoded.
 */
export function getTokenExpiryMinutes(token: string): number {
  const payload = decodeJwtPayload(token);
  if (!payload || !payload.exp) return -1;

  const nowSeconds = Math.floor(Date.now() / 1000);
  const diffSeconds = payload.exp - nowSeconds;
  return Math.floor(diffSeconds / 60);
}

/**
 * Returns true if the token expires within `thresholdMinutes` (default: 60 min),
 * or if it has already expired.
 *
 * The `minutesLeft >= 0` guard this used to have was backwards for an
 * already-expired token: `getTokenExpiryMinutes` returns a negative number the
 * further past expiry the token is (e.g. -1374 for a token that expired ~23h
 * ago), and `>= 0` excluded every one of those — meaning the auto-renewal cron
 * job in cronJobs.ts, which gates its entire renewal attempt on this function,
 * silently treated an already-dead token as "not expiring soon" and never
 * renewed it. Found while auditing why the Dhan feed (and the index/option
 * charts that depend on it) stayed stale despite valid TOTP auto-renewal
 * credentials being configured the whole time.
 */
export function isTokenExpiringSoon(token: string, thresholdMinutes = 60): boolean {
  const minutesLeft = getTokenExpiryMinutes(token);
  return minutesLeft <= thresholdMinutes;
}

/**
 * Reads the last auto-renewed Dhan token out of system_config, if one is on
 * record and it's fresher than whatever `process.env.DHAN_ACCESS_TOKEN` came
 * in with from docker-compose's env_file. Call this once at server startup,
 * before the DhanAdapter is constructed — that's the only point where
 * seeding process.env actually has any effect, since the adapter reads it
 * synchronously in its own constructor.
 *
 * Without this, every container recreate (rebuild, `--no-deps` redeploy, a
 * crash restart) throws away the most recently auto-renewed token and boots
 * on whatever static value last happened to be baked into the image's .env —
 * which may already be expired, leaving the feed down until the next
 * 30-minute cron check fires the TOTP renewal.
 */
export async function loadPersistedDhanToken(): Promise<string | null> {
  try {
    const row = await queryOne<{ value: string }>(`SELECT value FROM system_config WHERE key = 'DHAN_ACCESS_TOKEN'`);
    if (!row?.value) return null;

    const dbMinutesLeft = getTokenExpiryMinutes(row.value);
    const envMinutesLeft = process.env.DHAN_ACCESS_TOKEN ? getTokenExpiryMinutes(process.env.DHAN_ACCESS_TOKEN) : -Infinity;

    if (dbMinutesLeft > envMinutesLeft) {
      console.log(`[DhanTokenRefresh] Using persisted token from system_config (${dbMinutesLeft}m left vs ${envMinutesLeft}m from env).`);
      process.env.DHAN_ACCESS_TOKEN = row.value;
      return row.value;
    }
    return null;
  } catch (err) {
    console.error('[DhanTokenRefresh] Warning: Could not read persisted token from system_config:', err);
    return null;
  }
}

/**
 * Hot-swaps the Dhan access token in both:
 *  a) The live DhanAdapter instance (in-memory, immediate effect)
 *  b) The .env file (persists across restarts)
 * 
 * @param newToken - The fresh Dhan access token from https://login.dhan.co
 */
export async function updateDhanToken(newToken: string): Promise<{ success: boolean; message: string; expiresInMinutes?: number }> {
  if (!newToken || typeof newToken !== 'string' || newToken.split('.').length !== 3) {
    return { success: false, message: 'Invalid token format. Must be a valid JWT.' };
  }

  const expiresInMinutes = getTokenExpiryMinutes(newToken);
  if (expiresInMinutes < 0) {
    return { success: false, message: 'Token is already expired. Please generate a new one from https://login.dhan.co' };
  }

  // Update in process.env so subsequent instantiations or lookups see the fresh token
  process.env.DHAN_ACCESS_TOKEN = newToken;

  // 1. Hot-swap in the live adapter instance
  if (dhanAdapterRef) {
    try {
      await dhanAdapterRef.setAccessToken(newToken);
      console.log('[DhanTokenRefresh] ✅ Token hot-swapped in DhanAdapter. Reconnecting WebSocket...');
    } catch (err) {
      console.error('[DhanTokenRefresh] Failed to update adapter:', err);
    }
  } else {
    console.warn('[DhanTokenRefresh] DhanAdapter reference not set. Token not updated in adapter.');
  }

  // 2. Persist to .env file — best-effort only. This lives in the
  // container's writable layer, which does NOT survive a container
  // recreate (image rebuild, `docker compose up --no-deps`, a crash
  // restart) — it only helps a human inspecting a still-running container.
  try {
    const envPath = path.resolve(process.cwd(), '.env');
    if (fs.existsSync(envPath)) {
      let envContent = fs.readFileSync(envPath, 'utf-8');
      // Replace the existing DHAN_ACCESS_TOKEN line
      envContent = envContent.replace(
        /^DHAN_ACCESS_TOKEN=.*$/m,
        `DHAN_ACCESS_TOKEN=${newToken}`
      );
      fs.writeFileSync(envPath, envContent, 'utf-8');
      console.log('[DhanTokenRefresh] ✅ Token written to .env file successfully.');
    }
  } catch (err) {
    console.error('[DhanTokenRefresh] Warning: Could not write token to .env file:', err);
  }

  // 3. Persist to system_config — same table the admin "Market Data Provider"
  // screen already writes DHAN_ACCESS_TOKEN into. Postgres survives every
  // app-container recreate, so this (not the .env write above) is what
  // loadPersistedDhanToken() below reads at the next server boot.
  try {
    await execute(
      `INSERT INTO system_config (key, value, updated_at)
       VALUES ('DHAN_ACCESS_TOKEN', $1, NOW())
       ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW()`,
      [newToken]
    );
    console.log('[DhanTokenRefresh] ✅ Token persisted to system_config (survives container restarts).');
  } catch (err) {
    console.error('[DhanTokenRefresh] Warning: Could not persist token to system_config:', err);
  }

  const expiryHours = (expiresInMinutes / 60).toFixed(1);
  const successMsg = `✅ Dhan token updated successfully! New token expires in ${expiresInMinutes} minutes (~${expiryHours}h).`;
  console.log(`[DhanTokenRefresh] ${successMsg}`);

  // 3. Send Telegram confirmation (fire-and-forget, non-blocking)
  sendTelegramAlert(
    `🔑 <b>Trade Grow — Dhan Token Updated</b>\n\n` +
    `✅ New access token applied successfully.\n` +
    `⏳ Token valid for: <b>${expiryHours} hours</b>\n` +
    `📅 Alert will be sent 1 hour before expiry.`
  ).catch(() => {});

  return { success: true, message: successMsg, expiresInMinutes };
}
