<?php

namespace Database\Seeders;

use App\Models\PolicyDocument;
use App\Models\PolicyDocumentVersion;
use Illuminate\Database\Seeder;

/**
 * Seeds policy documents with a version-1 DRAFT each. Drafts are starting points for counsel,
 * are never published by seeding, and contain bracketed placeholders instead of invented facts.
 */
class PolicyDocumentSeeder extends Seeder
{
    private const REVIEW_BANNER = "> **DRAFT — requires legal and compliance review before publication.** Replace every [BRACKETED] placeholder with verified information.\n\n";

    public function run(): void
    {
        foreach (self::documents() as $slug => [$title, $category, $requiresConsent, $body]) {
            $document = PolicyDocument::query()->firstOrCreate(
                ['slug' => $slug],
                ['title' => $title, 'category' => $category, 'is_public' => true, 'requires_consent' => $requiresConsent],
            );

            if ($document->versions()->exists()) {
                continue;
            }

            $markdown = self::REVIEW_BANNER.$body;

            PolicyDocumentVersion::create([
                'policy_document_id' => $document->id,
                'version' => 1,
                'body_markdown' => $markdown,
                'content_hash' => hash('sha256', $markdown),
                'change_summary' => 'Initial draft template generated by the platform.',
            ]);
        }
    }

    /**
     * @return array<string, array{0: string, 1: string, 2: bool, 3: string}>
     */
    private static function documents(): array
    {
        return [
            'privacy-policy' => ['Privacy Policy', 'legal', true, <<<'MD'
# Privacy Policy

**Data controller:** [LEGAL ENTITY NAME], [REGISTERED ADDRESS].
**Contact for privacy requests:** [PRIVACY CONTACT EMAIL].

## What we collect
- Details you submit in forms: name, mobile number, email, city, and your message.
- Information needed to provide services, when you become a client: identity and address proof, risk-profile answers, agreements, invoices and payment references.
- Technical data: IP address, browser type, and pages visited. Analytics and advertising cookies are used only if you opt in.

## Why we use it
- To respond to your enquiry and, where you have agreed, to contact you by phone, WhatsApp or email.
- To assess suitability through a risk profile before providing services.
- To meet legal, regulatory, accounting and audit obligations.
- To secure our systems and prevent misuse.

## Your choices
You can withdraw marketing consent, ask for a copy of your data, or ask us to correct or delete it, subject to records we are legally required to keep. Write to [PRIVACY CONTACT EMAIL].

## Retention
We keep data only as long as required for the purpose collected and applicable record-keeping rules: [RETENTION PERIODS].

## Sharing
We share data only with service providers that process it on our behalf under contract (for example hosting, email, messaging and payment providers) and with authorities where required by law. We do not sell personal data.

## Changes
Each version of this policy is dated and archived. Effective date: [EFFECTIVE DATE].
MD],
            'terms-of-use' => ['Terms of Use', 'legal', true, <<<'MD'
# Terms of Use

These terms govern use of this website and the client portal operated by [LEGAL ENTITY NAME].

1. **No guarantee of returns.** Content and research are provided for information and are not a promise of profit or protection against loss.
2. **Eligibility.** Services are available only after onboarding, risk profiling and acceptance of the client agreement.
3. **Accounts.** You are responsible for keeping your login credentials confidential. Report suspected misuse to [SUPPORT EMAIL].
4. **Acceptable use.** Do not copy, redistribute or resell research or content without written permission.
5. **Availability.** We aim for continuous availability but do not guarantee uninterrupted access. Market data may be delayed or unavailable.
6. **Governing law.** [GOVERNING LAW AND JURISDICTION].
MD],
            'disclaimer' => ['Disclaimer', 'disclosure', false, <<<'MD'
# Disclaimer

Investments in the securities market are subject to market risks. Read all related documents carefully before investing.

- Research and educational content published by [LEGAL ENTITY NAME] does not guarantee any return and should not be the sole basis for an investment decision.
- Past performance of any security, sector, strategy or research recommendation does not indicate future results.
- Hypothetical or backtested results are not actual client results.
- Derivatives (futures and options) are leveraged instruments. Losses can exceed the initial margin.

**Regulatory status:** [DESCRIBE THE VERIFIED REGULATORY STATUS EXACTLY AS RECORDED IN THE VERIFIED REGULATORY PROFILE. DO NOT STATE ANY REGISTRATION THAT HAS NOT BEEN VERIFIED.]
MD],
            'risk-disclosure' => ['Risk Disclosure', 'disclosure', true, <<<'MD'
# Risk Disclosure

## Market risk
Prices of securities can fall as well as rise. You may lose part or all of the amount invested.

## Derivatives risk
Futures and options carry leverage. A small price movement can cause a large loss, and losses may exceed the margin deposited. Options can expire worthless.

## Liquidity and gap risk
Stop-loss levels in research are reference levels. Orders may execute at worse prices in fast or illiquid markets.

## Research limitations
Research is based on data available at its publication time, which may be incomplete, delayed or later revised. Every research item shows its publication time, validity period and invalidation condition.

## Use of technology and AI
Software, including AI-assisted tools, helps with data processing and drafting. Research is reviewed by [AUTHORIZED PERSON / ROLE] before publication. AI output can be wrong and is never treated as a final decision.
MD],
            'refund-policy' => ['Refund Policy', 'legal', true, <<<'MD'
# Refund Policy

[TO BE DRAFTED BY COUNSEL.] State clearly:
- whether fees are refundable, fully or partially, and in which situations;
- how a refund request is made and the response timeline;
- how a service cancellation affects access to research.

Do not describe a trial as a "guarantee".
MD],
            'investor-charter' => ['Investor Charter', 'disclosure', false, <<<'MD'
# Investor Charter

[INSERT THE INVESTOR CHARTER APPLICABLE TO THE VERIFIED REGULATORY CATEGORY, IN THE FORMAT PRESCRIBED BY THE REGULATOR, INCLUDING: vision and mission, business carried out, services provided to investors, grievance redressal mechanism, timelines, and investor rights and responsibilities.]

Source: [OFFICIAL SOURCE URL] · Retrieved: [DATE]
MD],
            'grievance-redressal' => ['Grievance Redressal', 'disclosure', false, <<<'MD'
# Grievance Redressal

1. **Raise a complaint:** email [GRIEVANCE EMAIL] or use the Support section in the client portal. You will receive a complaint number.
2. **Acknowledgement:** within [X] working days.
3. **Resolution target:** within [Y] days.
4. **Escalation:** Grievance Officer — [NAME], [EMAIL], [PHONE].
5. **Further escalation:** [APPLICABLE REGULATORY AND ONLINE DISPUTE RESOLUTION CHANNELS, WITH OFFICIAL LINKS].

We record every complaint, its handling steps and closure in our complaints register.
MD],
            'research-methodology' => ['Research Methodology', 'disclosure', false, <<<'MD'
# How Our Research Works

1. **Data.** Market, fundamental, derivatives and news data come from licensed providers. Every data point stores its source and timestamp. If data is missing or stale, research is not generated.
2. **Calculations.** Indicators (for example moving averages, RSI, MACD, ADX, ATR, VWAP) and statistics are computed by tested software, not by AI.
3. **Interpretation.** Analysts, assisted by AI drafting tools, interpret the computed data and write a thesis, scenarios, risk factors and an invalidation condition.
4. **Review.** Drafts pass automated consistency checks, a compliance review, and approval by [AUTHORIZED RESEARCH PERSON / ROLE] who did not author the draft.
5. **Publication.** Approved research is published with its time horizon, validity period, disclosures and version number. Published research is never edited; corrections are issued as new versions.
6. **Tracking.** Outcomes are recorded from market data after publication only, using a documented methodology. Research outcomes are not client returns.
MD],
            'ai-usage-policy' => ['AI Usage Policy', 'internal', false, <<<'MD'
# AI Usage Policy

- AI assists with summarizing, classifying and drafting. It does not calculate core financial metrics, decide regulatory matters, move money or publish research.
- AI tools access only the records the requesting employee is permitted to see.
- Every AI run is logged with model, prompt version, inputs, sources, output and reviewer.
- AI output shown to staff is labelled as an AI-generated interpretation.
- Client data sent to external AI providers is minimized. Approved providers: [LIST].
MD],
            'cookie-policy' => ['Cookie Policy', 'legal', false, <<<'MD'
# Cookie Policy

- **Necessary cookies** keep you signed in and protect forms against forgery. They cannot be switched off.
- **Analytics cookies** help us understand site usage. Used only with your consent.
- **Advertising cookies** measure campaigns. Used only with your consent.

You can change your choice at any time from the cookie settings link in the footer.
MD],
        ];
    }
}
