import express from 'express';
import http from 'http';
import cors from 'cors';
import helmet from 'helmet';
import dotenv from 'dotenv';
import path from 'path';

dotenv.config();

// P0-3 FIX: Validate critical environment variables before any other imports
import { validateStartupEnvironment } from './middleware/auth';
validateStartupEnvironment();

import { seedDatabase } from './db/init';
import { pool } from './db/pool';
import { MarketDataEngine } from './marketData/MarketDataEngine';
import { ExecutionEngine } from './trading/ExecutionEngine';
import { setupWebSocketServer } from './websocket/server';
import apiRouter from './routes/api';
import adminApiRouter from './routes/adminApi';
import { warRoomRouter } from './routes/warRoomRoutes';
import { ssoRouter } from './routes/ssoRoutes';
import { SafetyLock } from './services/SafetyLock';
import { startCronJobs, stopCronJobs, startMisAutoSquareOffJob, startExpirySettlementJob } from './utils/cronJobs';
import { startRmsLossMonitor } from './trading/RmsLossMonitor';
import { setDhanAdapterRef, loadPersistedDhanToken, isTokenExpiringSoon, autoGenerateDhanToken } from './utils/dhanTokenRefresh';
import { setFyersAdapterRef } from './utils/fyersTokenRefresh';

// Technical Assertion Lock on Server Startup
SafetyLock.assertSimulationOnly('ServerStartup');

// Global Process Resilience Guards — prevent unhandled rejections from crashing the HTTP server and returning 504s
process.on('unhandledRejection', (reason: any, promise: Promise<any>) => {
  console.error('[Process] ⚠️ Unhandled Rejection:', reason?.message || reason);
  if (reason?.stack) {
    console.error(reason.stack);
  }
});

process.on('uncaughtException', (err: Error) => {
  console.error('[Process] ⚠️ Uncaught Exception:', err.message);
  console.error(err.stack);
});

const app = express();
app.set('trust proxy', 1);
const server = http.createServer(app);
const PORT = process.env.PORT || 5000;

// ============================================================
// P1-5: Helmet.js Security Headers
// ============================================================
app.use(helmet({
  contentSecurityPolicy: {
    directives: {
      defaultSrc:    ["'self'"],
      scriptSrc:     ["'self'", "'unsafe-inline'", "'unsafe-eval'", "cdn.jsdelivr.net", "unpkg.com"],
      styleSrc:      ["'self'", "'unsafe-inline'", "fonts.googleapis.com"],
      fontSrc:       ["'self'", "fonts.gstatic.com"],
      imgSrc:        ["'self'", "data:", "blob:"],
      connectSrc:    ["'self'", "ws:", "wss:"],
      frameSrc:      ["'none'"],
      objectSrc:     ["'none'"]
    }
  },
  hsts: process.env.NODE_ENV === 'production'
    ? { maxAge: 31536000, includeSubDomains: true, preload: true }
    : false,
  noSniff:        true,
  xssFilter:      true,
  frameguard:     { action: 'deny' }
}));

// ============================================================
// P1-9: Explicit CORS — restrict to known origins
// ============================================================
const allowedOrigins = (process.env.ALLOWED_ORIGINS || 'http://localhost:5173,http://localhost:5000')
  .split(',')
  .map(o => o.trim());

app.use(cors({
  origin: (origin, callback) => {
    // Allow same-origin requests (no origin header)
    if (!origin) return callback(null, true);
    // Allow any localhost origin (any port) for local development
    if (origin.startsWith('http://localhost:') || origin.startsWith('http://127.0.0.1:')) {
      return callback(null, true);
    }
    // Allow explicitly whitelisted origins
    if (allowedOrigins.includes(origin)) {
      return callback(null, true);
    }
    callback(new Error(`CORS: Origin '${origin}' is not allowed`));
  },
  credentials: true,
  methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'],
  allowedHeaders: ['Content-Type', 'Authorization', 'Idempotency-Key', 'X-Request-ID']
}));


// JSON Parsers (5mb limit for QR code images and settings)
app.use(express.json({ limit: '5mb' }));
app.use(express.urlencoded({ extended: true, limit: '5mb' }));

// Register REST API Routes
app.use('/api/v1', apiRouter);
app.use('/api/v1/admin', adminApiRouter);
app.use('/api/v1', warRoomRouter);
app.use('/api/v1/auth/sso', ssoRouter);
app.use('/api/v1', ssoRouter);

// Global JSON error handler for all /api routes (Multer errors, parse errors, uncaught errors)
app.use('/api', (err: any, _req: express.Request, res: express.Response, next: express.NextFunction) => {
  if (err) {
    console.error('[API Handler Error]', err.message || err);
    if (res.headersSent) {
      return next(err);
    }
    const statusCode = err.status || err.statusCode || (err.name === 'MulterError' ? 400 : 500);
    return res.status(statusCode).json({
      success: false,
      error: {
        code: err.code || (err.name === 'MulterError' ? 'UPLOAD_ERROR' : 'INTERNAL_ERROR'),
        message: err.message || 'An unexpected error occurred during request processing'
      }
    });
  }
  next();
});

// ============================================================
// Startup: DB Init, Immediate Port Binding & Non-Blocking Async Services
// ============================================================
async function startServer() {
  try {
    // 1. Initialize database schema & migrations (fast)
    await seedDatabase();

    // 1b. Seed the most recently auto-renewed Dhan token from system_config,
    // if it's fresher than the static value docker-compose's env_file just
    // loaded. Must happen before the first MarketDataEngine.getInstance()
    // call below — that's what constructs DhanAdapter, which reads
    // process.env.DHAN_ACCESS_TOKEN synchronously in its own constructor.
    try {
      const persistedToken = await loadPersistedDhanToken();
      if (persistedToken) process.env.DHAN_ACCESS_TOKEN = persistedToken;

      // Auto-renew if token is expired or expiring in < 30 mins
      if (!process.env.DHAN_ACCESS_TOKEN || isTokenExpiringSoon(process.env.DHAN_ACCESS_TOKEN, 30)) {
        console.log('[Startup] 🔑 Dhan token is expired or expiring soon, auto-generating fresh 24h token via TOTP...');
        const autoRes = await autoGenerateDhanToken();
        if (autoRes.success && autoRes.accessToken) {
          process.env.DHAN_ACCESS_TOKEN = autoRes.accessToken;
          console.log('[Startup] ✅ Fresh 24h Dhan token generated on startup!');
        }
      }
    } catch (err: any) {
      console.error('[Startup] Warning: Dhan token persistence lookup failed, continuing with env value:', err.message);
    }

    // 2. Serve Frontend Static Files in Production
    const clientDistPath = path.resolve(__dirname, '../../client/dist');
    app.use(express.static(clientDistPath));
    app.get('*', (req, res, next) => {
      if (req.path.startsWith('/api') || req.path.startsWith('/ws')) return next();
      res.sendFile(path.join(clientDistPath, 'index.html'), (err) => {
        if (err) res.status(200).send('Trade Grow — Smart Trading Platform API Running. Client build pending.');
      });
    });

    // 3. Start HTTP Server IMMEDIATELY to prevent NGINX 504 Gateway Time-outs
    server.listen(PORT, () => {
      console.log(`=======================================================`);
      console.log(`🌱 TRADE GROW — SMART TRADING PLATFORM LISTENING ON PORT ${PORT}`);
      console.log(`🔒 SAFETY MODE: VIRTUAL PAPER TRADING ONLY (REAL MONEY DISABLED)`);
      console.log(`📊 MARKET DATA: ${MarketDataEngine.getInstance().getActiveProviderName()}`);
      console.log(`🛡️  SECURITY: Helmet.js, CORS restricted, Rate limiting active`);
      console.log(`=======================================================`);
    });

    // Align keep-alive timeouts with reverse proxy / Cloudflare / Nginx (avoids silent 502s)
    server.keepAliveTimeout = 65000;
    server.headersTimeout = 66000;

    // 4. Run Heavy Market Data Engines & Background Services Asynchronously (Non-Blocking)
    (async () => {
      try {
        const isPrimary = (process.env.PROCESS_ROLE || 'primary') !== 'worker';
        const { InstrumentMasterService } = await import('./marketData/InstrumentMasterService');
        await InstrumentMasterService.getInstance().initializeOnStartup();

        if (isPrimary) {
          console.log('[Startup] PROCESS_ROLE is primary — initializing upstream broker market data feed.');
          await MarketDataEngine.getInstance().initialize();
        } else {
          console.log('[Startup] PROCESS_ROLE is worker — broker market data feed handled by primary node.');
        }

        // NSE scraper & AccuracyCheck DISABLED — Dhan provides all data
        // import('./services/ReconciliationMonitorService') — keep monitor but at 5 min interval
        import('./services/ReconciliationMonitorService')
          .then(({ reconciliationMonitor }) => reconciliationMonitor.start(300000))
          .catch((err) => console.error('[Startup] Failed to start ReconciliationMonitorService:', err.message));

        ExecutionEngine.start();
        setupWebSocketServer(server);

        startMisAutoSquareOffJob();
        console.log('[Startup] ✅ RMS auto square-off scheduler started.');

        startExpirySettlementJob();
        console.log('[Startup] ✅ Contract Expiry Settlement scheduler started (15:30 IST daily).');

        // Startup expired contract reconciliation check (settle any lingering past-expired contracts immediately)
        import('./trading/ExpirySettlementEngine')
          .then(({ ExpirySettlementEngine }) => ExpirySettlementEngine.settleExpiredContracts())
          .catch((err) => console.error('[Startup] Failed to run initial expiry settlement check:', err.message));

        startRmsLossMonitor();
        console.log('[Startup] ✅ RMS continuous loss-tier monitor started.');

        const engine = MarketDataEngine.getInstance();
        const dhanProvider = engine.getDhanAdapter();
        if (dhanProvider && typeof dhanProvider.getAccessToken === 'function') {
          setDhanAdapterRef(dhanProvider);
          startCronJobs(() => dhanProvider.getAccessToken());
          console.log('[Startup] ✅ Dhan token cron jobs started (30-min expiry check + 08:30 AM IST reminder).');
        } else {
          console.warn('[Startup] ⚠️ DhanAdapter not found — cron jobs not started.');
        }

        console.log('[Startup] ✅ Fyers provider DISABLED. Running Dhan-only mode.');
        console.log('[Startup] ✅ All background market data engines & WebSocket services initialized cleanly.');
      } catch (bgErr: any) {
        console.error('[Startup Background Warning]', bgErr.message || bgErr);
      }
    })();

    // ── Graceful Shutdown Handler (SIGTERM & SIGINT) ─────────────────────────
    const handleShutdown = async (signal: string) => {
      console.log(`[Process] Received ${signal}. Initiating graceful connection draining and shutdown...`);
      const forceExitTimeout = setTimeout(() => {
        console.error('[Process] Forced shutdown after 25s grace timeout exceeded.');
        process.exit(1);
      }, 25000);
      forceExitTimeout.unref();

      try {
        server.close(() => {
          console.log('[HTTP] HTTP listener closed.');
        });
        const { shutdownWebSocketServer } = await import('./websocket/server');
        await shutdownWebSocketServer();
        ExecutionEngine.stop();
        await pool.end();
        console.log('[Process] Graceful shutdown completed cleanly.');
        process.exit(0);
      } catch (err: any) {
        console.error('[Process] Error during graceful shutdown:', err.message);
        process.exit(1);
      }
    };

    process.on('SIGTERM', () => handleShutdown('SIGTERM'));
    process.on('SIGINT', () => handleShutdown('SIGINT'));

  } catch (err: any) {
    console.error('[FATAL] Server startup failed:', err.message);
    console.error(err.stack);
    process.exit(1);
  }
}

startServer();

export { app, server };
