<?php

namespace App\Console\Commands;

use Illuminate\Console\Attributes\Description;
use Illuminate\Console\Attributes\Signature;
use Illuminate\Console\Command;

#[Signature('rbac:matrix {--path= : Output file (default: ../docs/RBAC_MATRIX.md)}')]
#[Description('Generate the RBAC matrix document from config/rbac.php')]
class RbacMatrix extends Command
{
    public function handle(): int
    {
        $roles = config('rbac.roles');
        $abbrev = [];
        foreach (array_keys($roles) as $i => $name) {
            $abbrev[$name] = 'R'.str_pad((string) ($i + 1), 2, '0', STR_PAD_LEFT);
        }

        $lines = [
            '# RBAC Matrix',
            '',
            '> Generated by `php artisan rbac:matrix` from `backend/config/rbac.php`. Do not edit by hand.',
            '',
            '## Enforcement layers',
            '',
            '1. **Permission** — route middleware `can:<permission>` (this matrix).',
            '2. **Record scope** — policies and query scopes: `*.view_own` → assigned records, `*.view_team` → records of the user\'s team, `*.view_all` → everything.',
            '3. **Separation of duties** — enforced in domain services regardless of permissions:',
            '   - Nobody can change their own roles, deactivate themselves, or change their own research authorization.',
            '   - Privileged roles ('.implode(', ', config('rbac.privileged_roles')).') can only be granted or revoked by holders of `roles.assign_privileged`.',
            '   - The last active Super Admin cannot be removed or deactivated.',
            '   - Regulatory profile versions are verified by someone other than their author/submitter; policy versions are approved by someone other than their author.',
            '   - `'.implode('`, `', config('rbac.authorized_person_permissions')).'` additionally require `employees.is_authorized_research_person`, set only by holders of `research_persons.authorize`, and the approver must not be the author (Phase 5).',
            '   - Manual payment verification requires two different people; allocation submitter ≠ approver (Phase 4).',
            '4. **2FA** — roles marked below require TOTP enrollment and a verified 2FA session before any admin, workspace or portal endpoint responds.',
            '',
            '## Roles',
            '',
            '| Code | Role | Staff | 2FA required | Privileged | Permissions |',
            '|---|---|---|---|---|---|',
        ];

        foreach ($roles as $name => $role) {
            $lines[] = sprintf('| %s | %s (`%s`) | %s | %s | %s | %d |',
                $abbrev[$name], $role['label'], $name,
                $role['staff'] ? 'Yes' : 'No',
                $role['requires_2fa'] ? 'Yes' : 'No',
                in_array($name, config('rbac.privileged_roles'), true) ? 'Yes' : 'No',
                count(array_unique($role['permissions'])));
        }

        $lines[] = '';
        $lines[] = '## Permission matrix';
        $lines[] = '';
        $lines[] = '● = granted. Column codes refer to the roles table above.';

        foreach (config('rbac.permissions') as $module => $permissions) {
            $lines[] = '';
            $lines[] = '### '.ucfirst($module);
            $lines[] = '';
            $lines[] = '| Permission | '.implode(' | ', $abbrev).' |';
            $lines[] = '|---|'.str_repeat(':-:|', count($abbrev));

            foreach ($permissions as $permission => $label) {
                $cells = array_map(fn ($role) => in_array($permission, $role['permissions'], true) ? '●' : '', $roles);
                $lines[] = "| `{$permission}`<br>{$label} | ".implode(' | ', $cells).' |';
            }
        }

        $path = $this->option('path') ?: base_path('../docs/RBAC_MATRIX.md');
        file_put_contents($path, implode("\n", $lines)."\n");
        $this->info("Wrote {$path}");

        return self::SUCCESS;
    }
}
